laravel 9 fix
mpociot/botman pull request #1307
Opened 2022-03-17 08:37 UTC by belivey

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-03-17 08:38 UTC, belivey commented
l9

2022-03-30 05:58 UTC, tinkeshwar requested changes

2022-03-30 05:58 UTC, tinkeshwar commented on composer.json
> +    "homepage": "http://github.com/belivey/botman",
change back to botman

2022-03-30 05:58 UTC, tinkeshwar commented on composer.json
> +    "name": "belivey/botman",
change back to botmat

2022-04-27 17:03 UTC, lptn reviewed
let's finally merge this PR

2022-04-27 17:03 UTC, lptn commented on composer.json
> +    "name": "belivey/botman",
```suggestion
    "name": "botman/botman",
```

2022-04-27 17:03 UTC, lptn commented on composer.json
> +    "homepage": "http://github.com/belivey/botman",
```suggestion
    "homepage": "http://github.com/botman/botman",
```

2022-04-29 18:31 UTC, closed without merging